#' Convert SACC codes into English
#'
#' @param data The dataframe or vector containing the SACC codified data to be converted into English.
#' @param col The column containing the SACC codified data
#' @param Country.region Indicate code to output Country/region of the SACC code
#' @param SACC_Major_group Indicate code to output SACC_Major_group of the SACC code
#' @param Region Indicate code to output World bank region of the SACC code
#' @description
#'
#' @return Plain English equivalents of SACC codified country names, SACC_Major_group and/or Region.
#' @export
#'
#' @examples SACC_convert(EDDC$country_of_birth)
#' @examples SACC_convert(APDC$country_of_birth_sacc)
#' @examples SACC_convert(APDC$country_of_birth_sacc, Country.region = TRUE, SACC_Major_group = TRUE, Region = TRUE)
#' @examples SACC_convert(EDDC$country_of_birth_sacc, Country.region = FALSE, Region = FALSE)


SACC_convert <- function(data, col, Country.region = TRUE, SACC_Major_group = TRUE, Region = TRUE) {

  SACC_conversions <- data.frame(SACC = c('1', '11', '1101', '1102', '1199', '12', '1201', '13', '1301', '1302', '1303', '1304', '14', '1401', '1402', '1403', '1404', '1405', '1406', '1407', '15', '1501', '1502', '1503', '1504', '1505', '1506', '1507', '1508', '1511', '1512', '1513', '1599', '16', '1601', '1602', '1603', '1604', '1605', '1606', '1607',
                                          '2', '21', '2102', '2103', '2104', '2105', '2106', '2107', '2108', '22', '2201', '23', '2301', '2302', '2303', '2304', '2305', '2306', '2307', '2308', '2311', '24', '2401', '2402', '2403', '2404', '2405', '2406', '2407', '2408',
                                          '3', '31', '3101', '3102', '3103', '3104', '3105', '3106', '3107', '3108', '32', '3201', '3202', '3203', '3204', '3205', '3206', '3207', '3208', '3211', '3212', '3214', '3215', '3216', '33', '3301', '3302', '3303', '3304', '3305', '3306', '3307', '3308', '3311', '3312',
                                          '4', '41', '4101', '4102', '4103', '4104', '4105', '4106', '4107', '4108', '4111', '42', '4201', '4202', '4203', '4204', '4205', '4206', '4207', '4208', '4211', '4212', '4213', '4214', '4215', '4216', '4217',
                                          '5', '51', '5101', '5102', '5103', '5104', '5105', '52', '5201', '5202', '5203', '5204', '5205', '5206',
                                          '6', '61', '6101', '6102', '6103', '6104', '6105', '62', '6201', '6202', '6203',
                                          '7', '71', '7101', '7102', '7103', '7104', '7105', '7106', '7107', '72', '7201', '7202', '7203', '7204', '7205', '7206', '7207', '7208', '7211',
                                          '8', '81', '8101', '8102', '8103', '8104', '82', '8201', '8202', '8203', '8204', '8205', '8206', '8207', '8208', '8211', '8212', '8213', '8214', '8215', '8216', '8299', '83', '8301', '8302', '8303', '8304', '8305', '8306', '8307', '8308', '84', '8401', '8402', '8403', '8404', '8405', '8406', '8407', '8408', '8411', '8412', '8413', '8414', '8415', '8416', '8417', '8421', '8422', '8423', '8424', '8425', '8426', '8427', '8428', '8431', '8432', '8433', '8434', '8435',
                                          '9', '91', '9101', '9102', '9103', '9104', '9105', '9106', '9107', '9108', '9111', '9112', '9113', '9114', '9115', '9116', '9117', '9118', '9121', '9122', '9123', '9124', '9125', '9126', '9127', '9128', '92', '9201', '9202', '9203', '9204', '9205', '9206', '9207', '9208', '9211', '9212', '9213', '9214', '9215', '9216', '9217', '9218', '9221', '9222', '9223', '9224', '9225', '9226', '9227', '9228', '9231', '9232', '9299'),
                                 Country.Region = c('OCEANIA AND ANTARCTICA', 'Australia', 'Australia', 'Norfolk Island', 'Australia', 'New Zealand', 'New Zealand', 'Melanesia', 'New Caledonia', 'Papua New Guinea', 'Solomon Islands', 'Vanuatu', 'Micronesia', 'Guam', 'Kiribati', 'Marshall Islands', 'Micronesia, Federated States of', 'Nauru', 'Northern Mariana Islands', 'Palau', 'Polynesia (excludes Hawaii)', 'Cook Islands', 'Fiji', 'French Polynesia', 'Niue', 'Samoa',
                                                    'Samoa, American', 'Tokelau', 'Tonga', 'Tuvalu', 'Wallis and Futuna', 'Pitcairn Islands', 'Polynesia (excludes Hawaii), nec', 'Antarctica', 'Adelie Land (France)', 'Argentinian Antarctic Territory', 'Australian Antarctic Territory', 'British Antarctic Territory', 'Chilean Antarctic Territory', 'Queen Maud Land (Norway)', 'Ross Dependency (New Zealand)', 'NORTH-WEST EUROPE', ' United Kingdom, Channel Islands and Isle of Man',
                                                    'England', 'Isle of Man', 'Northern Ireland', 'Scotland', 'Wales', 'Guernsey', 'Jersey', 'Ireland', 'Ireland', 'Western Europe', 'Austria', 'Belgium', 'France', 'Germany', 'Liechtenstein', 'Luxembourg', 'Monaco', 'Netherlands', 'Switzerland', 'Northern Europe', 'Denmark', 'Faroe Islands', 'Finland', 'Greenland', 'Iceland', 'Norway', 'Sweden', 'Aland Islands', 'SOUTHERN AND EASTERN EUROPE', 'Southern Europe', 'Andorra', 'Gibraltar',
                                                    'Holy See', 'Italy', 'Malta', 'Portugal', 'San Marino', 'Spain', 'South Eastern Europe', 'Albania', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'North Macedonia', 'Greece', 'Moldova', 'Romania', 'Slovenia', 'Montenegro', 'Serbia', 'Kosovo', 'Eastern Europe', 'Belarus', 'Czechia', 'Estonia', 'Hungary', 'Latvia', 'Lithuania', 'Poland', 'Russian Federation', 'Slovakia', 'Ukraine', 'NORTH AFRICA and the MIDDLE EAST', 'North Africa',
                                                    'Algeria', 'Egypt', 'Libya', 'Morocco', 'Sudan', 'Tunisia', 'Western Sahara', 'Spanish North Africa', 'South Sudan', 'Middle East', 'Bahrain', 'Gaza Strip and West Bank', 'Iran', 'Iraq', 'Israel', 'Jordan', 'Kuwait', 'Lebanon', 'Oman', 'Qatar', 'Saudi Arabia', 'Syria', 'Türkiye', 'United Arab Emirates', 'Yemen', 'SOUTH-EAST ASIA', 'Mainland South-East Asia', 'Myanmar', 'Cambodia', 'Laos', 'Thailand', 'Vietnam', 'Maritime South-East Asia', 'Brunei Darussalam',
                                                    'Indonesia', 'Malaysia', 'Philippines', 'Singapore', 'Timor-Leste', 'NORTH-EAST ASIA', 'Chinese Asia (includes Mongolia)', 'China (excludes SARs and Taiwan)', 'Hong Kong (SAR of China)', 'Macau (SAR of China)', 'Mongolia', 'Taiwan ', 'Japan and the Koreas', 'Japan', "Korea, Democratic People's Republic of (North)", 'Korea, Republic of (South)', 'SOUTHERN and CENTRAL ASIA', ' Southern Asia', 'Bangladesh', 'Bhutan', 'India', 'Maldives', 'Nepal', 'Pakistan', 'Sri Lanka',
                                                    'Central Asia', 'Afghanistan', 'Armenia', 'Azerbaijan', 'Georgia', 'Kazakhstan', 'Kyrgyzstan', 'Tajikistan', 'Turkmenistan', 'Uzbekistan', 'AMERICAS', 'Northern America', 'Bermuda', 'Canada', 'St Pierre and Miquelon', 'United States of America', 'South America', 'Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Falkland Islands', 'French Guiana', 'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela', 'South America, nec', 'Central America',
                                                    'Belize', 'Costa Rica', 'El Salvador', 'Guatemala', 'Honduras', 'Mexico', 'Nicaragua', 'Panama', 'Caribbean', 'Anguilla', 'Antigua and Barbuda', 'Aruba', 'Bahamas', 'Barbados', 'Cayman Islands', 'Cuba', 'Dominica', 'Dominican Republic', 'Grenada', 'Guadeloupe', 'Haiti', 'Jamaica', 'Martinique', 'Montserrat', 'Puerto Rico', 'St Kitts and Nevis', 'St Lucia', 'St Vincent and the Grenadines', 'Trinidad and Tobago', 'Turks and Caicos Islands', 'Virgin Islands, British ',
                                                    'Virgin Islands, United States', 'St Barthelemy', 'St Martin (French part)', 'Bonaire, Sint Eustatius and Saba', 'Curacao', 'Sint Maarten (Dutch part)', 'SUB-SAHARAN AFRICA', 'Central and West Africa', 'Benin', 'Burkina Faso', 'Cameroon', 'Cabo Verde', 'Central African Republic', 'Chad', 'Congo, Republic of', 'Congo, Democratic Republic of', "Cote d'Ivoire", 'Equatorial Guinea', 'Gabon', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Liberia', 'Mali', 'Mauritania', 'Niger',
                                                    'Nigeria', 'Sao Tome and Principe', 'Senegal', 'Sierra Leone', 'Togo', 'Southern and East Africa', 'Angola', 'Botswana', 'Burundi', 'Comoros', 'Djibouti', 'Eritrea', 'Ethiopia', 'Kenya', 'Lesotho', 'Madagascar', 'Malawi', 'Mauritius', 'Mayotte', 'Mozambique', 'Namibia', 'Reunion', 'Rwanda', 'St Helena', 'Seychelles', 'Somalia', 'South Africa', 'Eswatini', 'Tanzania', 'Uganda', 'Zambia', 'Zimbabwe', 'Southern and East Africa, nec'),
                                 SACC_Major_group = c('OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA',
                                                      'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA',
                                                      'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'OCEANIA AND ANTARCTICA', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE',
                                                      'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'NORTH-WEST EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE',
                                                      'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE',
                                                      'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'SOUTHERN AND EASTERN EUROPE', 'NORTH AFRICA and the MIDDLE EAST',
                                                      'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST',
                                                      'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'NORTH AFRICA and the MIDDLE EAST', 'SOUTH-EAST ASIA', 'SOUTH-EAST ASIA', 'SOUTH-EAST ASIA', 'SOUTH-EAST ASIA',
                                                      'SOUTH-EAST ASIA', 'SOUTH-EAST ASIA', 'SOUTH-EAST ASIA', 'SOUTH-EAST ASIA', 'SOUTH-EAST ASIA', 'SOUTH-EAST ASIA', 'SOUTH-EAST ASIA', 'SOUTH-EAST ASIA', 'SOUTH-EAST ASIA', 'SOUTH-EAST ASIA', 'NORTH-EAST ASIA', 'NORTH-EAST ASIA', 'NORTH-EAST ASIA', 'NORTH-EAST ASIA', 'NORTH-EAST ASIA', 'NORTH-EAST ASIA', 'NORTH-EAST ASIA', 'NORTH-EAST ASIA', 'NORTH-EAST ASIA', 'NORTH-EAST ASIA', 'NORTH-EAST ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA',
                                                      'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'SOUTHERN and CENTRAL ASIA', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS',
                                                      'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS',
                                                      'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'AMERICAS', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA',
                                                      'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA',
                                                      'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', 'SUB-SAHARAN AFRICA', ''),
                                 Region = c('', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', '', 'East Asia & Pacific', 'East Asia & Pacific',
                                            'East Asia & Pacific', 'East Asia & Pacific', '', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', '', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific',
                                            '', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', '', 'East Asia & Pacific', 'East Asia & Pacific',
                                            '', '', 'East Asia & Pacific', '', '', '', '', '', '', '', '', 'Europe & Central Asia', '', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia',
                                            'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia',
                                            'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia',
                                            'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia',
                                            'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Middle East & North Africa', 'Europe & Central Asia',
                                            'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia',
                                            'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia',
                                            'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia',
                                            'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa', 'Sub-Saharan Africa', 'Middle East & North Africa',
                                            'Middle East & North Africa', 'Middle East & North Africa', 'Sub-Saharan Africa', 'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa',
                                            'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa', 'Middle East & North Africa',
                                            'Europe & Central Asia', 'Middle East & North Africa', 'Middle East & North Africa', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific',
                                            'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', '', '', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific',
                                            'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', 'East Asia & Pacific', '', 'South Asia', 'South Asia', 'South Asia', 'South Asia', 'South Asia', 'South Asia', 'South Asia', 'South Asia', 'Europe & Central Asia', 'South Asia',
                                            'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', 'Europe & Central Asia', '', 'North America', 'North America', 'North America', 'North America',
                                            'North America', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', '', 'Latin America & Caribbean', 'Latin America & Caribbean',
                                            'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean',
                                            'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean',
                                            'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean',
                                            'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean',
                                            'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', 'Latin America & Caribbean', '', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa',
                                            'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa',
                                            'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Middle East & North Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa',
                                            'Sub-Saharan Africa', 'Sub-Saharan Africa', '', 'Sub-Saharan Africa', 'Sub-Saharan Africa', '', 'Sub-Saharan Africa', '', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', 'Sub-Saharan Africa', ''))

  cols <- c("Country.region", "SACC_Major_group", "Region")
  if (!Country.region) cols <- setdiff(cols, "Country.region")
  if (!SACC_Major_group) cols <- setdiff(cols, "SACC_Major_group")
  if (!Region) cols <- setdiff(cols, "Region")

  data <- as.data.frame(data)

  # Perform left join on selected columns
  data %>%
    left_join(SACC_conversions,
              # select(data, cols),
              by = as.character("col"))
}
